/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWeeklyMissionsRouteImport } from './routes/_authenticated/weekly-missions'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated/rewards'
import { Route as AuthenticatedQuestsRouteImport } from './routes/_authenticated/quests'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHallOfFameRouteImport } from './routes/_authenticated/hall-of-fame'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClassroomsRouteImport } from './routes/_authenticated/classrooms'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedBonusCenterRouteImport } from './routes/_authenticated/bonus-center'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAiChatRouteImport } from './routes/_authenticated/ai-chat'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedFlashcardsIndexRouteImport } from './routes/_authenticated/flashcards.index'
import { Route as AuthenticatedExamIndexRouteImport } from './routes/_authenticated/exam.index'
import { Route as AuthenticatedClassroomsIndexRouteImport } from './routes/_authenticated/classrooms.index'
import { Route as AuthenticatedQuizNewRouteImport } from './routes/_authenticated/quiz.new'
import { Route as AuthenticatedQuizJoinRouteImport } from './routes/_authenticated/quiz.join'
import { Route as AuthenticatedQuizSessionIdRouteImport } from './routes/_authenticated/quiz.$sessionId'
import { Route as AuthenticatedFlashcardsDeckIdRouteImport } from './routes/_authenticated/flashcards.$deckId'
import { Route as AuthenticatedExamNewRouteImport } from './routes/_authenticated/exam.new'
import { Route as AuthenticatedExamJoinRouteImport } from './routes/_authenticated/exam.join'
import { Route as AuthenticatedExamDemoRouteImport } from './routes/_authenticated/exam.demo'
import { Route as AuthenticatedExamExamIdRouteImport } from './routes/_authenticated/exam.$examId'
import { Route as AuthenticatedClassroomsIdRouteImport } from './routes/_authenticated/classrooms.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTeachersRouteImport } from './routes/_authenticated/admin/teachers'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin/students'
import { Route as AuthenticatedAdminRoomsRouteImport } from './routes/_authenticated/admin/rooms'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedExamExamIdIndexRouteImport } from './routes/_authenticated/exam.$examId.index'
import { Route as AuthenticatedExamExamIdReportRouteImport } from './routes/_authenticated/exam.$examId.report'
import { Route as AuthenticatedExamExamIdEditRouteImport } from './routes/_authenticated/exam.$examId.edit'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeeklyMissionsRoute =
  AuthenticatedWeeklyMissionsRouteImport.update({
    id: '/weekly-missions',
    path: '/weekly-missions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuestsRoute = AuthenticatedQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHallOfFameRoute = AuthenticatedHallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassroomsRoute = AuthenticatedClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBonusCenterRoute =
  AuthenticatedBonusCenterRouteImport.update({
    id: '/bonus-center',
    path: '/bonus-center',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiChatRoute = AuthenticatedAiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedFlashcardsIndexRoute =
  AuthenticatedFlashcardsIndexRouteImport.update({
    id: '/flashcards/',
    path: '/flashcards/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExamIndexRoute = AuthenticatedExamIndexRouteImport.update({
  id: '/exam/',
  path: '/exam/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassroomsIndexRoute =
  AuthenticatedClassroomsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClassroomsRoute,
  } as any)
const AuthenticatedQuizNewRoute = AuthenticatedQuizNewRouteImport.update({
  id: '/quiz/new',
  path: '/quiz/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuizJoinRoute = AuthenticatedQuizJoinRouteImport.update({
  id: '/quiz/join',
  path: '/quiz/join',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuizSessionIdRoute =
  AuthenticatedQuizSessionIdRouteImport.update({
    id: '/quiz/$sessionId',
    path: '/quiz/$sessionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFlashcardsDeckIdRoute =
  AuthenticatedFlashcardsDeckIdRouteImport.update({
    id: '/flashcards/$deckId',
    path: '/flashcards/$deckId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExamNewRoute = AuthenticatedExamNewRouteImport.update({
  id: '/exam/new',
  path: '/exam/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamJoinRoute = AuthenticatedExamJoinRouteImport.update({
  id: '/exam/join',
  path: '/exam/join',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamDemoRoute = AuthenticatedExamDemoRouteImport.update({
  id: '/exam/demo',
  path: '/exam/demo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamExamIdRoute = AuthenticatedExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassroomsIdRoute =
  AuthenticatedClassroomsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedClassroomsRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTeachersRoute =
  AuthenticatedAdminTeachersRouteImport.update({
    id: '/admin/teachers',
    path: '/admin/teachers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/admin/students',
    path: '/admin/students',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoomsRoute = AuthenticatedAdminRoomsRouteImport.update({
  id: '/admin/rooms',
  path: '/admin/rooms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExamExamIdIndexRoute =
  AuthenticatedExamExamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExamExamIdRoute,
  } as any)
const AuthenticatedExamExamIdReportRoute =
  AuthenticatedExamExamIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedExamExamIdRoute,
  } as any)
const AuthenticatedExamExamIdEditRoute =
  AuthenticatedExamExamIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedExamExamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/checkin': typeof CheckinRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/ai-chat': typeof AuthenticatedAiChatRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bonus-center': typeof AuthenticatedBonusCenterRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/classrooms': typeof AuthenticatedClassroomsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hall-of-fame': typeof AuthenticatedHallOfFameRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quests': typeof AuthenticatedQuestsRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/weekly-missions': typeof AuthenticatedWeeklyMissionsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/rooms': typeof AuthenticatedAdminRoomsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/classrooms/$id': typeof AuthenticatedClassroomsIdRoute
  '/exam/$examId': typeof AuthenticatedExamExamIdRouteWithChildren
  '/exam/demo': typeof AuthenticatedExamDemoRoute
  '/exam/join': typeof AuthenticatedExamJoinRoute
  '/exam/new': typeof AuthenticatedExamNewRoute
  '/flashcards/$deckId': typeof AuthenticatedFlashcardsDeckIdRoute
  '/quiz/$sessionId': typeof AuthenticatedQuizSessionIdRoute
  '/quiz/join': typeof AuthenticatedQuizJoinRoute
  '/quiz/new': typeof AuthenticatedQuizNewRoute
  '/classrooms/': typeof AuthenticatedClassroomsIndexRoute
  '/exam/': typeof AuthenticatedExamIndexRoute
  '/flashcards/': typeof AuthenticatedFlashcardsIndexRoute
  '/exam/$examId/edit': typeof AuthenticatedExamExamIdEditRoute
  '/exam/$examId/report': typeof AuthenticatedExamExamIdReportRoute
  '/exam/$examId/': typeof AuthenticatedExamExamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/checkin': typeof CheckinRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/ai-chat': typeof AuthenticatedAiChatRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bonus-center': typeof AuthenticatedBonusCenterRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hall-of-fame': typeof AuthenticatedHallOfFameRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quests': typeof AuthenticatedQuestsRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/weekly-missions': typeof AuthenticatedWeeklyMissionsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/rooms': typeof AuthenticatedAdminRoomsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/classrooms/$id': typeof AuthenticatedClassroomsIdRoute
  '/exam/demo': typeof AuthenticatedExamDemoRoute
  '/exam/join': typeof AuthenticatedExamJoinRoute
  '/exam/new': typeof AuthenticatedExamNewRoute
  '/flashcards/$deckId': typeof AuthenticatedFlashcardsDeckIdRoute
  '/quiz/$sessionId': typeof AuthenticatedQuizSessionIdRoute
  '/quiz/join': typeof AuthenticatedQuizJoinRoute
  '/quiz/new': typeof AuthenticatedQuizNewRoute
  '/classrooms': typeof AuthenticatedClassroomsIndexRoute
  '/exam': typeof AuthenticatedExamIndexRoute
  '/flashcards': typeof AuthenticatedFlashcardsIndexRoute
  '/exam/$examId/edit': typeof AuthenticatedExamExamIdEditRoute
  '/exam/$examId/report': typeof AuthenticatedExamExamIdReportRoute
  '/exam/$examId': typeof AuthenticatedExamExamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/book': typeof BookRoute
  '/checkin': typeof CheckinRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/ai-chat': typeof AuthenticatedAiChatRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/bonus-center': typeof AuthenticatedBonusCenterRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/classrooms': typeof AuthenticatedClassroomsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hall-of-fame': typeof AuthenticatedHallOfFameRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/quests': typeof AuthenticatedQuestsRoute
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/_authenticated/weekly-missions': typeof AuthenticatedWeeklyMissionsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/rooms': typeof AuthenticatedAdminRoomsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/classrooms/$id': typeof AuthenticatedClassroomsIdRoute
  '/_authenticated/exam/$examId': typeof AuthenticatedExamExamIdRouteWithChildren
  '/_authenticated/exam/demo': typeof AuthenticatedExamDemoRoute
  '/_authenticated/exam/join': typeof AuthenticatedExamJoinRoute
  '/_authenticated/exam/new': typeof AuthenticatedExamNewRoute
  '/_authenticated/flashcards/$deckId': typeof AuthenticatedFlashcardsDeckIdRoute
  '/_authenticated/quiz/$sessionId': typeof AuthenticatedQuizSessionIdRoute
  '/_authenticated/quiz/join': typeof AuthenticatedQuizJoinRoute
  '/_authenticated/quiz/new': typeof AuthenticatedQuizNewRoute
  '/_authenticated/classrooms/': typeof AuthenticatedClassroomsIndexRoute
  '/_authenticated/exam/': typeof AuthenticatedExamIndexRoute
  '/_authenticated/flashcards/': typeof AuthenticatedFlashcardsIndexRoute
  '/_authenticated/exam/$examId/edit': typeof AuthenticatedExamExamIdEditRoute
  '/_authenticated/exam/$examId/report': typeof AuthenticatedExamExamIdReportRoute
  '/_authenticated/exam/$examId/': typeof AuthenticatedExamExamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/checkin'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/activity'
    | '/ai-chat'
    | '/analytics'
    | '/bonus-center'
    | '/bookings'
    | '/classrooms'
    | '/dashboard'
    | '/hall-of-fame'
    | '/profile'
    | '/quests'
    | '/rewards'
    | '/weekly-missions'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/rooms'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/classrooms/$id'
    | '/exam/$examId'
    | '/exam/demo'
    | '/exam/join'
    | '/exam/new'
    | '/flashcards/$deckId'
    | '/quiz/$sessionId'
    | '/quiz/join'
    | '/quiz/new'
    | '/classrooms/'
    | '/exam/'
    | '/flashcards/'
    | '/exam/$examId/edit'
    | '/exam/$examId/report'
    | '/exam/$examId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/checkin'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/activity'
    | '/ai-chat'
    | '/analytics'
    | '/bonus-center'
    | '/bookings'
    | '/dashboard'
    | '/hall-of-fame'
    | '/profile'
    | '/quests'
    | '/rewards'
    | '/weekly-missions'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/rooms'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/classrooms/$id'
    | '/exam/demo'
    | '/exam/join'
    | '/exam/new'
    | '/flashcards/$deckId'
    | '/quiz/$sessionId'
    | '/quiz/join'
    | '/quiz/new'
    | '/classrooms'
    | '/exam'
    | '/flashcards'
    | '/exam/$examId/edit'
    | '/exam/$examId/report'
    | '/exam/$examId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/book'
    | '/checkin'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/activity'
    | '/_authenticated/ai-chat'
    | '/_authenticated/analytics'
    | '/_authenticated/bonus-center'
    | '/_authenticated/bookings'
    | '/_authenticated/classrooms'
    | '/_authenticated/dashboard'
    | '/_authenticated/hall-of-fame'
    | '/_authenticated/profile'
    | '/_authenticated/quests'
    | '/_authenticated/rewards'
    | '/_authenticated/weekly-missions'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/rooms'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/teachers'
    | '/_authenticated/admin/users'
    | '/_authenticated/classrooms/$id'
    | '/_authenticated/exam/$examId'
    | '/_authenticated/exam/demo'
    | '/_authenticated/exam/join'
    | '/_authenticated/exam/new'
    | '/_authenticated/flashcards/$deckId'
    | '/_authenticated/quiz/$sessionId'
    | '/_authenticated/quiz/join'
    | '/_authenticated/quiz/new'
    | '/_authenticated/classrooms/'
    | '/_authenticated/exam/'
    | '/_authenticated/flashcards/'
    | '/_authenticated/exam/$examId/edit'
    | '/_authenticated/exam/$examId/report'
    | '/_authenticated/exam/$examId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BookRoute: typeof BookRoute
  CheckinRoute: typeof CheckinRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weekly-missions': {
      id: '/_authenticated/weekly-missions'
      path: '/weekly-missions'
      fullPath: '/weekly-missions'
      preLoaderRoute: typeof AuthenticatedWeeklyMissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quests': {
      id: '/_authenticated/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof AuthenticatedQuestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hall-of-fame': {
      id: '/_authenticated/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof AuthenticatedHallOfFameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classrooms': {
      id: '/_authenticated/classrooms'
      path: '/classrooms'
      fullPath: '/classrooms'
      preLoaderRoute: typeof AuthenticatedClassroomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bonus-center': {
      id: '/_authenticated/bonus-center'
      path: '/bonus-center'
      fullPath: '/bonus-center'
      preLoaderRoute: typeof AuthenticatedBonusCenterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-chat': {
      id: '/_authenticated/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AuthenticatedAiChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/flashcards/': {
      id: '/_authenticated/flashcards/'
      path: '/flashcards'
      fullPath: '/flashcards/'
      preLoaderRoute: typeof AuthenticatedFlashcardsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exam/': {
      id: '/_authenticated/exam/'
      path: '/exam'
      fullPath: '/exam/'
      preLoaderRoute: typeof AuthenticatedExamIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classrooms/': {
      id: '/_authenticated/classrooms/'
      path: '/'
      fullPath: '/classrooms/'
      preLoaderRoute: typeof AuthenticatedClassroomsIndexRouteImport
      parentRoute: typeof AuthenticatedClassroomsRoute
    }
    '/_authenticated/quiz/new': {
      id: '/_authenticated/quiz/new'
      path: '/quiz/new'
      fullPath: '/quiz/new'
      preLoaderRoute: typeof AuthenticatedQuizNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz/join': {
      id: '/_authenticated/quiz/join'
      path: '/quiz/join'
      fullPath: '/quiz/join'
      preLoaderRoute: typeof AuthenticatedQuizJoinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz/$sessionId': {
      id: '/_authenticated/quiz/$sessionId'
      path: '/quiz/$sessionId'
      fullPath: '/quiz/$sessionId'
      preLoaderRoute: typeof AuthenticatedQuizSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flashcards/$deckId': {
      id: '/_authenticated/flashcards/$deckId'
      path: '/flashcards/$deckId'
      fullPath: '/flashcards/$deckId'
      preLoaderRoute: typeof AuthenticatedFlashcardsDeckIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exam/new': {
      id: '/_authenticated/exam/new'
      path: '/exam/new'
      fullPath: '/exam/new'
      preLoaderRoute: typeof AuthenticatedExamNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exam/join': {
      id: '/_authenticated/exam/join'
      path: '/exam/join'
      fullPath: '/exam/join'
      preLoaderRoute: typeof AuthenticatedExamJoinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exam/demo': {
      id: '/_authenticated/exam/demo'
      path: '/exam/demo'
      fullPath: '/exam/demo'
      preLoaderRoute: typeof AuthenticatedExamDemoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exam/$examId': {
      id: '/_authenticated/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/exam/$examId'
      preLoaderRoute: typeof AuthenticatedExamExamIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classrooms/$id': {
      id: '/_authenticated/classrooms/$id'
      path: '/$id'
      fullPath: '/classrooms/$id'
      preLoaderRoute: typeof AuthenticatedClassroomsIdRouteImport
      parentRoute: typeof AuthenticatedClassroomsRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/teachers': {
      id: '/_authenticated/admin/teachers'
      path: '/admin/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AuthenticatedAdminTeachersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/rooms': {
      id: '/_authenticated/admin/rooms'
      path: '/admin/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AuthenticatedAdminRoomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/exam/$examId/': {
      id: '/_authenticated/exam/$examId/'
      path: '/'
      fullPath: '/exam/$examId/'
      preLoaderRoute: typeof AuthenticatedExamExamIdIndexRouteImport
      parentRoute: typeof AuthenticatedExamExamIdRoute
    }
    '/_authenticated/exam/$examId/report': {
      id: '/_authenticated/exam/$examId/report'
      path: '/report'
      fullPath: '/exam/$examId/report'
      preLoaderRoute: typeof AuthenticatedExamExamIdReportRouteImport
      parentRoute: typeof AuthenticatedExamExamIdRoute
    }
    '/_authenticated/exam/$examId/edit': {
      id: '/_authenticated/exam/$examId/edit'
      path: '/edit'
      fullPath: '/exam/$examId/edit'
      preLoaderRoute: typeof AuthenticatedExamExamIdEditRouteImport
      parentRoute: typeof AuthenticatedExamExamIdRoute
    }
  }
}

interface AuthenticatedClassroomsRouteChildren {
  AuthenticatedClassroomsIdRoute: typeof AuthenticatedClassroomsIdRoute
  AuthenticatedClassroomsIndexRoute: typeof AuthenticatedClassroomsIndexRoute
}

const AuthenticatedClassroomsRouteChildren: AuthenticatedClassroomsRouteChildren =
  {
    AuthenticatedClassroomsIdRoute: AuthenticatedClassroomsIdRoute,
    AuthenticatedClassroomsIndexRoute: AuthenticatedClassroomsIndexRoute,
  }

const AuthenticatedClassroomsRouteWithChildren =
  AuthenticatedClassroomsRoute._addFileChildren(
    AuthenticatedClassroomsRouteChildren,
  )

interface AuthenticatedExamExamIdRouteChildren {
  AuthenticatedExamExamIdEditRoute: typeof AuthenticatedExamExamIdEditRoute
  AuthenticatedExamExamIdReportRoute: typeof AuthenticatedExamExamIdReportRoute
  AuthenticatedExamExamIdIndexRoute: typeof AuthenticatedExamExamIdIndexRoute
}

const AuthenticatedExamExamIdRouteChildren: AuthenticatedExamExamIdRouteChildren =
  {
    AuthenticatedExamExamIdEditRoute: AuthenticatedExamExamIdEditRoute,
    AuthenticatedExamExamIdReportRoute: AuthenticatedExamExamIdReportRoute,
    AuthenticatedExamExamIdIndexRoute: AuthenticatedExamExamIdIndexRoute,
  }

const AuthenticatedExamExamIdRouteWithChildren =
  AuthenticatedExamExamIdRoute._addFileChildren(
    AuthenticatedExamExamIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAiChatRoute: typeof AuthenticatedAiChatRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBonusCenterRoute: typeof AuthenticatedBonusCenterRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedClassroomsRoute: typeof AuthenticatedClassroomsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHallOfFameRoute: typeof AuthenticatedHallOfFameRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuestsRoute: typeof AuthenticatedQuestsRoute
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedWeeklyMissionsRoute: typeof AuthenticatedWeeklyMissionsRoute
  AuthenticatedAdminRoomsRoute: typeof AuthenticatedAdminRoomsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminTeachersRoute: typeof AuthenticatedAdminTeachersRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedExamExamIdRoute: typeof AuthenticatedExamExamIdRouteWithChildren
  AuthenticatedExamDemoRoute: typeof AuthenticatedExamDemoRoute
  AuthenticatedExamJoinRoute: typeof AuthenticatedExamJoinRoute
  AuthenticatedExamNewRoute: typeof AuthenticatedExamNewRoute
  AuthenticatedFlashcardsDeckIdRoute: typeof AuthenticatedFlashcardsDeckIdRoute
  AuthenticatedQuizSessionIdRoute: typeof AuthenticatedQuizSessionIdRoute
  AuthenticatedQuizJoinRoute: typeof AuthenticatedQuizJoinRoute
  AuthenticatedQuizNewRoute: typeof AuthenticatedQuizNewRoute
  AuthenticatedExamIndexRoute: typeof AuthenticatedExamIndexRoute
  AuthenticatedFlashcardsIndexRoute: typeof AuthenticatedFlashcardsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAiChatRoute: AuthenticatedAiChatRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBonusCenterRoute: AuthenticatedBonusCenterRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedClassroomsRoute: AuthenticatedClassroomsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHallOfFameRoute: AuthenticatedHallOfFameRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuestsRoute: AuthenticatedQuestsRoute,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedWeeklyMissionsRoute: AuthenticatedWeeklyMissionsRoute,
  AuthenticatedAdminRoomsRoute: AuthenticatedAdminRoomsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminTeachersRoute: AuthenticatedAdminTeachersRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedExamExamIdRoute: AuthenticatedExamExamIdRouteWithChildren,
  AuthenticatedExamDemoRoute: AuthenticatedExamDemoRoute,
  AuthenticatedExamJoinRoute: AuthenticatedExamJoinRoute,
  AuthenticatedExamNewRoute: AuthenticatedExamNewRoute,
  AuthenticatedFlashcardsDeckIdRoute: AuthenticatedFlashcardsDeckIdRoute,
  AuthenticatedQuizSessionIdRoute: AuthenticatedQuizSessionIdRoute,
  AuthenticatedQuizJoinRoute: AuthenticatedQuizJoinRoute,
  AuthenticatedQuizNewRoute: AuthenticatedQuizNewRoute,
  AuthenticatedExamIndexRoute: AuthenticatedExamIndexRoute,
  AuthenticatedFlashcardsIndexRoute: AuthenticatedFlashcardsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BookRoute: BookRoute,
  CheckinRoute: CheckinRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
